### ISSUE TITLE
Investigate reports of Prism missing world loads when using MultiVerse

### ISSUE THREAD

**Issue by viveleroi** [darkhelmet-gaming/PrismRefracted#1]
As described here: https://github.com/AddstarMC/Prism-Bukkit/pull/297

Prism uses the `WorldLoadEvent` to register worlds and as a multiverse user myself I've never had any issues but if there's any further details, this is where we'll track it.

**Comment by Rothes** [comment]
That means we don't need to listen `CreateWorld` event! I raised an unnecessary question in that PR.
This related issues occasionally happens on some users and asks for help. They have to add those worlds manually no matter how many times they restart the server. Maybe MultiVerse may called this event earlier than Prism loaded?

**Comment by viveleroi** [comment]
For the time being, in v4, world entries are always created before activities are written to the database, so this won't be an issue. I'll leave it open to verify once test builds are available.

**Comment by Bobcat00** [comment]
Adding `softdepend: [WorldEdit,Multiverse-Core]` seems to solve this problem.

**Comment by Rothes** [comment]
> Adding `softdepend: [WorldEdit,Multiverse-Core]` seems to solve this problem in v3.

Yes - As for now, I haven't received those related messages after that patch.
